version: "3.8"
services:
  database:
    image: mongo:latest
    container_name: database
    environment:
      - MONGO_INITDB_DATABASE=pokemon
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    ports:
      - 27017:27017

  mongoimport:
    image: library/mongo:latest
    container_name: database-import
    links:
      - database
    env_file:
      - ./.env
    volumes:
      - ./data/pokemon.json:/src/data/pokemon.json
    command: mongoimport --host database --db pokemon --collection pokemon --username pokemon --password pokemon --file /src/data/pokemon.json --jsonArray

  pokemon:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - database
    restart: unless-stopped